spring.application.name=hubdash-api
server.port=8080
app.api-key=${API_KEY:dev-local-key}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hubdash}
spring.datasource.username=${DB_USER:hubdash}
spring.datasource.password=${DB_PASSWORD:hubdash}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.kafka.consumer.group-id=hubdash-health-etl
spring.kafka.consumer.auto-offset-reset=earliest
