CREATE TABLE health_raw_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at_raw VARCHAR(100) NOT NULL,
    weight_kg_raw VARCHAR(50),
    sleep_hours_raw DOUBLE PRECISION,
    notes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_health_raw_log_status ON health_raw_log(status);
