CREATE TABLE schedule_raw_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_raw VARCHAR(200) NOT NULL,
    start_at_raw VARCHAR(100) NOT NULL,
    end_at_raw VARCHAR(100) NOT NULL,
    location VARCHAR(200),
    description VARCHAR(1000),
    all_day_raw VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_schedule_raw_event_status ON schedule_raw_event(status);
