CREATE TABLE memo_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_raw VARCHAR(200) NOT NULL,
    content_raw VARCHAR(5000) NOT NULL,
    tags VARCHAR(300),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_memo_raw_status ON memo_raw(status);
