CREATE TABLE reminder_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_raw VARCHAR(200) NOT NULL,
    target_at_raw VARCHAR(50) NOT NULL,
    target_domain VARCHAR(50),
    target_entity_id BIGINT,
    sent_raw VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_reminder_raw_status ON reminder_raw(status);
