CREATE TABLE hub_raw_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id_raw VARCHAR(50) NOT NULL,
    title_raw VARCHAR(200) NOT NULL,
    url_raw VARCHAR(1000) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_hub_raw_link_status ON hub_raw_link(status);
