CREATE TABLE study_raw_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id_raw VARCHAR(50) NOT NULL,
    studied_at_raw VARCHAR(50) NOT NULL,
    minutes_raw VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_study_raw_progress_status ON study_raw_progress(status);
