CREATE TABLE life_raw_habit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id_raw VARCHAR(50) NOT NULL,
    performed_at_raw VARCHAR(50) NOT NULL,
    completed_raw VARCHAR(50) NOT NULL,
    notes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_life_raw_habit_log_status ON life_raw_habit_log(status);
