CREATE TABLE pknu_raw_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id_raw VARCHAR(50) NOT NULL,
    title_raw VARCHAR(200) NOT NULL,
    due_date_raw VARCHAR(50) NOT NULL,
    completed_raw VARCHAR(50) NOT NULL,
    notes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_pknu_raw_assignment_status ON pknu_raw_assignment(status);
