CREATE TABLE life_habit_weekly_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id BIGINT NOT NULL REFERENCES life_habit(id),
    week_start DATE NOT NULL,
    total_count INTEGER NOT NULL,
    completed_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_life_habit_weekly_stat_habit_week UNIQUE (habit_id, week_start)
);
