CREATE TABLE study_topic_weekly_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL REFERENCES study_topic(id),
    week_start DATE NOT NULL,
    session_count INTEGER NOT NULL,
    total_minutes INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_study_topic_weekly_stat_topic_week UNIQUE (topic_id, week_start)
);
