CREATE TABLE health_log_weekly_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    log_count INTEGER NOT NULL,
    avg_weight_kg DOUBLE PRECISION,
    avg_sleep_hours DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_health_log_weekly_stat_week UNIQUE (week_start)
);
