CREATE TABLE pknu_assignment_weekly_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES pknu_course(id),
    week_start DATE NOT NULL,
    total_count INTEGER NOT NULL,
    completed_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_pknu_assignment_weekly_stat_course_week UNIQUE (course_id, week_start)
);
