CREATE TABLE health_meal_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_record_id BIGINT NOT NULL REFERENCES health_meal_record(id),
    name VARCHAR(100) NOT NULL,
    calories INTEGER NOT NULL,
    carbs_g DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_health_meal_item_meal_record_id ON health_meal_item(meal_record_id);

-- 기존 끼니 1건이 들고 있던 영양 값은 음식 항목 1건으로 옮겨 데이터를 잃지 않는다.
INSERT INTO health_meal_item (meal_record_id, name, calories, carbs_g, protein_g, fat_g, sodium_mg, created_at, updated_at)
SELECT id, '기존 기록', calories, carbs_g, protein_g, fat_g, sodium_mg, created_at, updated_at
FROM health_meal_record;

ALTER TABLE health_meal_record
    DROP COLUMN calories,
    DROP COLUMN carbs_g,
    DROP COLUMN protein_g,
    DROP COLUMN fat_g,
    DROP COLUMN sodium_mg;
