CREATE TABLE health_meal_weekly_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start DATE NOT NULL,
    day_count INTEGER NOT NULL,
    avg_calories DOUBLE PRECISION NOT NULL,
    avg_carbs_g DOUBLE PRECISION NOT NULL,
    avg_protein_g DOUBLE PRECISION NOT NULL,
    avg_fat_g DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_health_meal_weekly_stat_week UNIQUE (week_start)
);
