-- 노션 → 허브 링크 한 방향 동기화 (이슈 #107)
-- 동기화 소스: 노션 DB(행) 또는 부모 페이지(하위 페이지)를 허브 카테고리에 연결한다.
CREATE TABLE notion_sync_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notion_id VARCHAR(32) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    hub_category_id BIGINT NOT NULL REFERENCES hub_category(id) ON DELETE CASCADE,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notion_sync_source_notion_id UNIQUE (notion_id)
);

-- 이미 가져온 노션 페이지 — 같은 페이지를 두 번 링크로 만들지 않기 위한 기록.
-- raw_hub_link_id가 비어 있으면 동기화가 만든 게 아니라 원래 있던 링크(#94 이관분)와 짝지은 것이다.
CREATE TABLE notion_synced_page (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES notion_sync_source(id) ON DELETE CASCADE,
    notion_page_id VARCHAR(32) NOT NULL,
    raw_hub_link_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notion_synced_page_source_page UNIQUE (source_id, notion_page_id)
);
