-- 냉장고: 자주 먹는/가진 음식을 저장해 두고 끼니에 눌러서 넣는다 (이슈 #130)
CREATE TABLE health_food (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    calories INTEGER NOT NULL,
    carbs_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    serving VARCHAR(50),
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
