-- 식단 목표 (한 행만 쓰는 설정). 값이 null이면 그 항목은 목표 없음 (이슈 #131)
CREATE TABLE health_diet_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carbs_g DOUBLE PRECISION,
    carbs_rule VARCHAR(10) NOT NULL,
    fat_g DOUBLE PRECISION,
    fat_rule VARCHAR(10) NOT NULL,
    protein_g DOUBLE PRECISION,
    protein_rule VARCHAR(10) NOT NULL,
    calories INTEGER,
    calories_rule VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
