-- 일정 연동 계정 정보 (이슈 #227). 웹 설정 화면에서 입력·변경한다.
-- config_json: 비밀이 아닌 설정(노션 일정 DB ID, iCloud 캘린더 이름, 표시용 계정 이름)
-- secret_enc: 비밀값(노션 토큰, Apple 앱 암호)을 AES-GCM으로 암호화한 값. 키는 환경변수 CREDENTIAL_KEY
CREATE TABLE integration_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    config_json TEXT,
    secret_enc TEXT,
    last_verified_at TIMESTAMP,
    last_error VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_integration_credential_provider UNIQUE (provider)
);
