-- 일정 동기화 (이슈 #228): 어디서 온 일정인지와 원본 ID
-- MANUAL = HubDash에서 직접 만든 일정 — 동기화는 절대 건드리지 않는다
ALTER TABLE schedule_event ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE schedule_event ADD COLUMN external_id VARCHAR(200);
-- 같은 출처의 같은 원본은 하나만 (MANUAL은 external_id가 NULL이라 제약에 걸리지 않는다)
ALTER TABLE schedule_event ADD CONSTRAINT uk_schedule_event_source_external UNIQUE (source, external_id);

-- 동기화 실행 기록 (소스별 한 줄)
CREATE TABLE sync_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NOT NULL,
    ok BOOLEAN NOT NULL,
    added INTEGER NOT NULL,
    updated INTEGER NOT NULL,
    deleted INTEGER NOT NULL,
    error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_sync_run_source_started ON sync_run(source, started_at);
