CREATE TABLE health_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at DATE NOT NULL,
    weight_kg DOUBLE PRECISION,
    sleep_hours DOUBLE PRECISION,
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_health_log_recorded_at ON health_log(recorded_at);

CREATE TABLE health_meal_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumed_at TIMESTAMP NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    calories INTEGER NOT NULL,
    carbs_g DOUBLE PRECISION,
    protein_g DOUBLE PRECISION,
    fat_g DOUBLE PRECISION,
    sodium_mg DOUBLE PRECISION,
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_health_meal_record_consumed_at ON health_meal_record(consumed_at);

CREATE TABLE health_workout_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_at DATE NOT NULL,
    type VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    calories_burned INTEGER,
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_health_workout_log_performed_at ON health_workout_log(performed_at);
