CREATE TABLE pknu_semester (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE pknu_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_id BIGINT NOT NULL REFERENCES pknu_semester(id),
    name VARCHAR(100) NOT NULL,
    professor VARCHAR(50),
    credit INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_pknu_course_semester_id ON pknu_course(semester_id);

CREATE TABLE pknu_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES pknu_course(id),
    title VARCHAR(200) NOT NULL,
    due_date DATE NOT NULL,
    completed BOOLEAN NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_pknu_assignment_course_id ON pknu_assignment(course_id);
