CREATE TABLE reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    target_at TIMESTAMP NOT NULL,
    target_domain VARCHAR(50),
    target_entity_id BIGINT,
    sent BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_reminder_target_at ON reminder(target_at);
